version: '3.8'

services:

    postgres:
        build:
            context: ./keycloak/db
        image: postgres:keycloak
        container_name: postgres-keycloak
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    keycloak:
        image: jboss/keycloak:latest #11.0.2
        container_name: keycloak
        ports:
            - 3533:8080
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=postgres
            - DB_ADDR=postgres-keycloak
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=keycloak
        depends_on:
            - postgres

    db:
        build:
            context: ./db
        image: postgres:lespromapp
        container_name: postgres-app
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: lesprom

    backend:
        build:
            context: ../lesprom-back
        image: lesprom-back
        container_name: lesprom-back
        ports:
            - 8080:8080
        environment:
            APP_PROFILE: test

    frontend:
        build:
            context: ../lesprom-front
        image: lesprom-front
        container_name: lesprom-front
        ports:
            - 8081:80